# Auto generated docker container, using a prebuilt image
# This will result in faster build times since we won't have to build the
# container each time.
FROM gcr.io/{{PROJECT}}/mlab-vis-pipeline:latest